import assert from 'node:assert/strict';
import { AUTONOMY_LEVELS, autonomyAllows, suggestNextActions, writeAutonomyLevel } from '../src/agent/autonomyPolicy.js';
assert.equal(autonomyAllows(AUTONOMY_LEVELS.READ_ONLY, 'read'), true);
assert.equal(autonomyAllows(AUTONOMY_LEVELS.PREPARE, 'prepare-patch'), true);
assert.equal(autonomyAllows(AUTONOMY_LEVELS.PREPARE, 'write'), false);
assert.equal(autonomyAllows(AUTONOMY_LEVELS.READ_ONLY, 'execute'), false);
assert.throws(() => writeAutonomyLevel('full-auto'), /Invalid autonomy/);
const suggestions = suggestNextActions({ tasks: [{ status: 'verified' }], workspaceTree: [{ name: 'src', type: 'folder', children: [] }] });
assert.ok(suggestions.some(item => item.type === 'consider-tests'));
assert.ok(suggestions.some(item => item.type === 'documentation'));
console.log('autonomy policy tests passed');
