import assert from 'node:assert/strict';
import { ToolRegistry } from '../src/tools/toolRegistry.js';
import { ApprovalGate, executeWithApproval } from '../src/tools/toolApproval.js';
import { normalizeWorkspacePath } from '../src/workspace/workspaceStore.js';
const registry = new ToolRegistry().register({ name: 'write_file', permission: 'write', execute: async () => 'written' });
const gate = new ApprovalGate();
const request = gate.request('write_file', { path: 'x' });
await assert.rejects(() => executeWithApproval(registry, gate, request.id), /explicit user approval/);
const request2 = gate.request('write_file', { path: 'x' });
assert.equal(await executeWithApproval(registry, gate, request2.id, true), 'written');
assert.equal(normalizeWorkspacePath('project\\src/'), 'project/src');
assert.throws(() => normalizeWorkspacePath('../outside'), /parent traversal/);
console.log('safety tests passed');
