services:
  - type: web
    name: toddler-control-plane
    runtime: docker
    rootDir: backend
    plan: free
    healthCheckPath: /health
  - type: web
    name: toddler-inference
    runtime: docker
    rootDir: backend
    dockerfilePath: ./inference_service/Dockerfile
    plan: free
    healthCheckPath: /health
