export const BUILTIN_SKILLS = Object.freeze([
  Object.freeze({
    id: 'requirements-echo',
    name: 'Requirements Echo',
    version: '1.0.0',
    description: 'Reconstructs long, ambiguous, dictated, or self-correcting requests before any code action. Use when a request contains reversals, many constraints, or unclear assumptions.',
    triggers: ['think out loud', 'voice note', 'long request', 'requirements', 'actually', 'wait', 'scrap that', 'must', 'constraint'],
    allowedTools: [],
    permissions: { workspaceRead: false, workspaceWrite: false, network: false, execute: false },
    instructions: 'Do not edit. Return Mission, Locked Decisions, Open Questions, Reversals, Parked Ideas, and Model Assumptions. Ask the user to approve the brief before continuing.',
    role: 'requirements',
  }),
  Object.freeze({
    id: 'scope-creep-detector',
    name: 'Scope Creep Detector',
    version: '1.0.0',
    description: 'Compares a proposed patch with the user request and flags unrelated paths, dependencies, configuration changes, oversized changes, and public API churn.',
    triggers: ['scope creep', 'too broad', 'unrelated changes', 'split patch', 'review diff', 'fix', 'refactor', 'implement'],
    allowedTools: ['validate_patch'],
    permissions: { workspaceRead: true, workspaceWrite: false, network: false, execute: false },
    instructions: 'Classify every changed file as keep, split, or justify. Treat lexical mismatch as a warning, not proof.',
    role: 'reviewer',
  }),
  Object.freeze({
    id: 'patch-reviewer',
    name: 'Patch Reviewer',
    version: '1.0.0',
    description: 'Reviews unified diffs for request coverage, correctness, maintainability, regression risk, and missing tests before approval.',
    triggers: ['patch', 'diff', 'code review', 'fix', 'refactor', 'implement', 'change code'],
    allowedTools: ['read_file', 'validate_patch'],
    permissions: { workspaceRead: true, workspaceWrite: false, network: false, execute: false },
    instructions: 'Review only. Never apply a patch. Return pass or revise with specific file and hunk evidence.',
    role: 'reviewer',
  }),
  Object.freeze({
    id: 'security-reviewer',
    name: 'Security Reviewer',
    version: '1.0.0',
    description: 'Scans added code for credential access, injection, dynamic execution, unsafe HTML, broad permissions, networking, and shell-like behavior.',
    triggers: ['security', 'auth', 'credential', 'secret', 'permission', 'network', 'patch', 'diff'],
    allowedTools: ['validate_patch'],
    permissions: { workspaceRead: true, workspaceWrite: false, network: false, execute: false },
    instructions: 'Report concrete evidence and severity. Do not invent vulnerabilities without a matching added line.',
    role: 'reviewer',
  }),
  Object.freeze({
    id: 'test-planner',
    name: 'Test Planner',
    version: '1.0.0',
    description: 'Suggests focused tests and validation steps from changed paths and behavior without executing commands on Android.',
    triggers: ['test', 'verify', 'validation', 'regression', 'fix', 'implement', 'patch'],
    allowedTools: ['read_file', 'search'],
    permissions: { workspaceRead: true, workspaceWrite: false, network: false, execute: false },
    instructions: 'Propose the smallest meaningful tests. Android must never execute a shell command.',
    role: 'verifier',
  }),
]);
