import * as tf from '@tensorflow/tfjs';
import * as mobilenet from '@tensorflow-models/mobilenet';
import * as knnClassifier from '@tensorflow-models/knn-classifier';

let cachedNet = null;
const getMobileNet = async () => {
  if (!cachedNet) {
    cachedNet = await mobilenet.load();
  }
  return cachedNet;
};

// Crucial Memory Fix: MobileNet expects 224x224. Loading full 4K images 
// into WebGL 1000 times causes mobile browsers to instantly hit Out-of-Memory (Aw, Snap!).
// This draws the image to a tiny 224x224 canvas FIRST, so we only pass the tiny canvas to TFJS.
const loadAndResizeImage = (srcOrFile) => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    const isFile = typeof srcOrFile !== 'string';
    const url = isFile ? URL.createObjectURL(srcOrFile) : srcOrFile;

    // Only apply crossOrigin to remote URLs, not local blob/data URIs
    if (!isFile && !url.startsWith('blob:') && !url.startsWith('data:')) {
      img.crossOrigin = "anonymous";
    }

    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = 224;
      canvas.height = 224;
      const ctx = canvas.getContext('2d');
      // Draw scaled down version
      ctx.drawImage(img, 0, 0, 224, 224);
      
      if (isFile) URL.revokeObjectURL(url);
      resolve(canvas); // Resolve with the tiny canvas, not the giant image!
    };
    
    img.onerror = (e) => {
      if (isFile) URL.revokeObjectURL(url);
      reject(e);
    };
    
    img.src = url;
  });
};

export const trainVisionModel = async (imageFiles, onProgress) => {
  await tf.ready();
  onProgress('Initializing Engine...');
  const classifier = knnClassifier.create();
  
  onProgress('Loading Base Feature Extractor (MobileNet)...');
  const net = await getMobileNet();
  
  for (let i = 0; i < imageFiles.length; i++) {
    const file = imageFiles[i];
    const parts = file.webkitRelativePath.split('/');
    const label = parts.length > 1 ? parts[parts.length - 2] : 'unknown';
    
    if (i % 5 === 0 || i === imageFiles.length - 1) {
      onProgress(`Extracting features: Image ${i + 1} of ${imageFiles.length}...`);
      await tf.nextFrame();
      // Force aggressive garbage collection breathing room on mobile
      await new Promise(r => setTimeout(r, 10));
    }
    
    try {
      const canvas = await loadAndResizeImage(file);
      
      // Use tf.tidy to automatically clean up the intermediate tensors generated by infer()
      const activation = tf.tidy(() => net.infer(canvas, true));
      classifier.addExample(activation, label);
      
      activation.dispose(); // Manually dispose the activation after adding it to KNN
    } catch (e) {
      console.warn('Skipping unreadable image', file.name);
    }
  }
  
  onProgress('Polishing Network Weights...');
  await tf.nextFrame();
  
  let dataset = classifier.getClassifierDataset();
  let datasetObj = {};
  Object.keys(dataset).forEach((key) => {
    let data = dataset[key].dataSync();
    datasetObj[key] = { shape: dataset[key].shape, data: Array.from(data) };
  });
  
  classifier.dispose();
  return JSON.stringify(datasetObj);
};

export const predictVisionImage = async (imageSrc, datasetJson) => {
  await tf.ready();
  const classifier = knnClassifier.create();
  const net = await getMobileNet();
  
  let datasetObj = typeof datasetJson === 'string' ? JSON.parse(datasetJson) : datasetJson;
  let tensorObj = {};
  Object.keys(datasetObj).forEach((key) => {
    tensorObj[key] = tf.tensor(datasetObj[key].data, datasetObj[key].shape);
  });
  classifier.setClassifierDataset(tensorObj);
  
  const canvas = await loadAndResizeImage(imageSrc);
  const activation = tf.tidy(() => net.infer(canvas, true));
  const result = await classifier.predictClass(activation);
  
  activation.dispose();
  classifier.dispose();
  
  return { prediction: result.label, confidence: result.confidences[result.label] || 0 };
};

export const retrainVisionImage = async (imageSrc, datasetJson, correctLabel) => {
  await tf.ready();
  const classifier = knnClassifier.create();
  const net = await getMobileNet();
  
  let datasetObj = typeof datasetJson === 'string' ? JSON.parse(datasetJson) : datasetJson;
  let tensorObj = {};
  Object.keys(datasetObj).forEach((key) => {
    tensorObj[key] = tf.tensor(datasetObj[key].data, datasetObj[key].shape);
  });
  classifier.setClassifierDataset(tensorObj);
  
  const canvas = await loadAndResizeImage(imageSrc);
  const activation = tf.tidy(() => net.infer(canvas, true));
  classifier.addExample(activation, correctLabel);
  
  let newDataset = classifier.getClassifierDataset();
  let newDatasetObj = {};
  Object.keys(newDataset).forEach((key) => {
    let data = newDataset[key].dataSync();
    newDatasetObj[key] = { shape: newDataset[key].shape, data: Array.from(data) };
  });
  
  activation.dispose();
  classifier.dispose();
  
  return JSON.stringify(newDatasetObj);
};